config_test: Add setup and new_test functions.
function setup has to be used by test scenario to setup their
environnement (aka expected test result, pretty name...).

function new_test takes one argument (the test name) and generate a test
skel.
Use: . config_test newtest "testname"

Signed-off-by: Jean-François Morcillo <jfm@laposte.net>

diff --git a/tests/config_test b/tests/config_test
--- a/tests/config_test
+++ b/tests/config_test
@@ -1,3 +1,51 @@
 REMOTE=/tmp/test.git
 
 . ~/.mgtconfig
+
+function setup () {
+    # expected result of the test
+    [[ -z $EXP_RES ]] && { echo 'Error: $EXP_RES is not defined'; exit 1; }
+    echo "$EXP_RES" > exp_res
+
+        # Test name that will be displayed before running
+    [[ ! -z $PRETTY_NAME ]] && echo "$PRETTY_NAME" > pretty_name
+
+    # Interactive test
+    [[ ! -z $INTERACTIVE ]] && touch interactive
+
+    # put input of the test, if any, into input: echo "values" > input
+    [[ ! -z $INPUTS ]] && echo $INPUTS > input
+
+    exit 0
+}
+
+function new_test () {
+    [[ $# -ne 1 ]] && { echo "Error: only one argument is need: test_name"; exit 1; }
+    mkdir -p "$1"
+    cat > "$1/test_script.sh" << EOL
+#!/bin/bash
+
+. ../config_test
+
+# Expected result of the test
+#EXP_RES="ok|nok"
+
+# Test name that will be displayed before running
+#PRETTY_NAME=""
+
+# Interactive test
+#INTERACTIVE=true
+
+# Inputs of the test
+#INPUTS="a b c"
+
+
+[[ "\$1" == "setup" ]] && setup
+
+# Test body goes here
+EOL
+
+    echo "Test skel generated: $1/test_script.sh"
+}
+
+[[ "$1" == "newtest" ]] && new_test $2
